Flask-JWT/app/models.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import create_engine, Column, Integer, String, Table, ForeignKey
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker, relationship, backref

engine = create_engine('sqlite:///database.db')

Base = declarative_base()

# Define the User database model
class User(Base):
    __tablename__ = 'users'
    id = Column(Integer, primary_key=True)
    username = Column(String(50), unique=True ,nullable=False)
    password = Column(String(100), nullable=False)
    task = relationship('Task', back_populates='user',cascade='all, delete-orphan')

# Define the Task database model
class Task(Base):
    __tablename__ = 'tasks'
    id = Column(Integer, primary_key=True)
    title = Column(String(50), nullable=False)
    user_id = Column(Integer, ForeignKey('users.id'), nullable=False)

    user = relationship('User', back_populates='task')

session = sessionmaker(bind=engine)

Session = session()

Base.metadata.create_all(engine)

Flask-JWT/app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Length

# This class is for the user to login
class LoginForm(FlaskForm):
    username = StringField('username', validators = [DataRequired(), Length(min=4, max=20)])
    password = PasswordField('password', validators = [DataRequired(), Length(min=8, max=20)])
    submit = SubmitField('Login')

# This class is for the user to register
class RegisterForm(FlaskForm):
    username = StringField('username', validators = [DataRequired(), Length(min=4, max=20)])
    password = PasswordField('password', validators = [DataRequired(), Length(min=8, max=20)])
    submit = SubmitField('Register')

# This class is for the user to create a task
class TaskForm(FlaskForm):
    title = StringField('title', validators = [DataRequired(), Length(min=4, max=20)])
    submit = SubmitField('Create Task')

Flask-JWT/app/__init__.py
from flask import Flask

def create_app():
    app = Flask(__name__)

    # Configurations
    from config import Config
    app.config.from_object(Config)

    # Initialize JWT with the app
    from flask_jwt_extended import JWTManager
    
    jwt = JWTManager(app)

    # Import and register blueprints
    from app.auth.routes import auth_bp
    from app.task.routes import task_bp

    app.register_blueprint(auth_bp, url_prefix='/')
    app.register_blueprint(task_bp, url_prefix='/task')

    return app

Flask-JWT/app/task/routes.py
from flask import Flask, Blueprint, render_template, redirect, url_for, jsonify, make_response, session, flash
from flask_jwt_extended import create_access_token, jwt_required, get_jwt_identity, create_refresh_token
from app.models import User, Session, Task
from app.forms import TaskForm

task_bp = Blueprint('task', __name__)


@task_bp.route('/add', methods=['GET', 'POST'])
def add():
    if 'user_id' not in session:
        return redirect(url_for('auth.Login'))
    
    form = TaskForm()
    if form.validate_on_submit():
            try:
                task = Task(title=form.title.data,user_id=session['user_id'])
                Session.add(task)
                Session.commit()
                flash('Task added successfully')
                return redirect(url_for('task.get_tasks'))
            except Exception as e:
                flash(f'Task addition failed: {str(e)}')
                Session.rollback()
    return render_template('task.html', form=form)

@task_bp.route('/display', methods=['GET'])
@jwt_required()
def get_tasks():
    user_id = get_jwt_identity()
    
    # Rollback if there's any uncommitted session state (though it's not usually necessary here)
    Session.rollback()
    
    tasks = Session.query(Task).filter_by(user_id=user_id).all()
    tasks_json = [{'id': task.id, 'title': task.title} for task in tasks]
    
    return jsonify(tasks_json)

@task_bp.route('/delete/<int:id>', methods=['GET'])
def delete(id):
    if 'user_id' in session:
        user_id = session['user_id']
    task = Session.query(Task).filter_by(user_id=user_id).filter_by(id=id).first()
    Session.delete(task)
    Session.commit()
    flash('Task deleted successfully')
    return redirect(url_for('task.get_tasks'))

Flask-JWT/app/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    hello world
    
</body>
</html>

Flask-JWT/app/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="login" method="POST">
        {{form.hidden_tag()}}
        <div>
            {{ form.username.label }}
            {{ form.username }} 
            {% for error in form.username.errors %} 
                {{ error }} 
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }}
            {{ form.password }} 
            {% for error in form.password.errors %} 
                {{ error }} 
            {% endfor %}
        </div>
        <div>
            {{ form.submit }}
        </div>
    </form>
</body>
</html>

Flask-JWT/app/templates/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="register" method="POST">
        {{form.hidden_tag()}}
        <div>
            {{ form.username.label }}
            {{ form.username }} 
            {% for error in form.username.errors %} 
                {{ error }} 
            {% endfor %}
        </div>
        <div>
            {{ form.password.label }}
            {{ form.password }} 
            {% for error in form.password.errors %} 
                {{ error }} 
            {% endfor %}
        </div>
        <div>
            {{ form.submit }}
        </div>
    </form>
</body>
</html>

Flask-JWT/app/templates/task.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Todo List</title>
</head>
<body>
    <h1>Add a Task</h1>
    <form action="{{ url_for('task.add') }}" method="POST">
        {{ form.hidden_tag() }}
        <div>
            {{ form.title.label }}
            {{ form.title }}
            {% for error in form.title.errors %}
                <span class="error">{{ error }}</span>
            {% endfor %}
        </div>
        <div>
            {{ form.submit }}
        </div>
    </form>

</body>
</html>